baseURL = 'https://grakke.github.io'
title = "Grakke's Blog"
theme = "hugo-coder"
languageCode = "en"
enableEmoji = true

defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"
# [services]
# [services.disqus]
# shortname = "blog-hehcvyfk3w"
# disqus_identifier = "blog"
# disqus_title = "blog"
# disqus_url =

[params]
author = "Henry Lee"
description = "Henry Lee's personal website"
keywords = "blog,developer,personal"
info = ["Full Stack DevOps", "Soccer Arsenal Fan"]
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false

math = true
# katex = true

enableTwemoji = true

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"

# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = [
	"'self'",
	"https://www.google-analytics.com",
	# "https://giscus.app/",
	# "https://disqus.com/",
	# "https://blog-hehcvyfk3w.disqus.com/",
	# "https://menrealitycalc.com/",
]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'", "https://menrealitycalc.com/", "https://utteranc.es/"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
	"'self'",
	"'unsafe-inline'",
	"https://fonts.googleapis.com/",
	"https://cdn.jsdelivr.net/",
	# "https://giscus.app/",
	# "https://blog-hehcvyfk3w.disqus.com/",
	# "https://disqus.com/",
	# "https://menrealitycalc.com/",
]
scriptsrc = [
	"'self'",
	"'unsafe-inline'",
	"https://www.google-analytics.com",
	"https://utteranc.es/",
	"https://cdn.jsdelivr.net/",
	# "https://giscus.app/",
	# "https://disqus.com/",
	# "https://blog-hehcvyfk3w.disqus.com/",
	# "https://menrealitycalc.com/",
]

prefetchsrc = ["'self'", "https://utteranc.es/"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = [
	"'self'",
	"https://www.google-analytics.com",
	"https://utteranc.es/",
	"https://cdn.jsdelivr.net/",
	# "https://giscus.app",
	# "https://disqus.com",
	# "https://blog-hehcvyfk3w.disqus.com/",
	# "https://menrealitycalc.com/",
]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/grakke/"

# [[params.social]]
# name = "Gitlab"
# icon = "fa fa-2x fa-gitlab"
# weight = 2
# url = "https://gitlab.com/johndoe/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/bluebird_gunner/"

# [[params.social]]
# name = "Douban"
# icon = "fa fa-2x fa-douban"
# weight = 4
# url = "https://www.douban.com/people/3418529/"

# [[params.social]]
# name = "Medium"
# icon = "fa fa-2x fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

[[params.social]]
name = "Wechat"
icon = "fa fa-2x fa-wechat"
weight = 6
url = "https://myhugosite.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 7
url = "https://grakke.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml"


[languages.en]
languageName = ":uk:"

# Menu links
[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.pt-cn]
languageName = ":cn:"
title = "Grakke"

[languages.pt-cn.params]
author = "GRAKKE'S BLOG"
info = ["Full Stack DevOps", "Soccer Arsenal Fan"]
description = "Sítio pessoal de João Ninguém"
keywords = "blog, desenvolvedor, pessoal"

[[languages.pt-cn.menu.main]]
name = "关于"
weight = 1
url = "about/"

[[languages.pt-cn.menu.main]]
name = "博客"
weight = 2
url = "posts/"

[[languages.pt-cn.menu.main]]
name = "项目"
weight = 3
url = "projects/"

[[languages.pt-cn.menu.main]]
name = "联系"
weight = 5
url = "contact/"

# [params.giscus]
# repo = "grakke/grakke.github.io"             # Repo where the comments will live
# category = "General"                         # "Q&A" Repo where the comments will live
# mapping = "pathname"                         # How Utterances will match comment to page
# label = "comment"                            # Label applied to issue by utteranc.es bot
# theme = "auto"                               # "preferred_color_scheme" What theme to use
# reactions_enabled = "1"
# emit_metadata = "0"
# lang="zh-CN"
# strict="0"
# repoID ="MDEwOlJlcG9zaXRvcnkzNjQ0MjcwMzc="
# categoryID="DIC_kwDOFbi3Hc4CAILH"
# reactionsEnabled="1"
# inputPosition="top"
# loading="lazy"

[params.utterances]
repo = "grakke/grakke.github.io"
issueTerm = "og:title"
theme = "preferred-color-scheme"

[services]
[services.googleAnalytics]
ID = 'G-JBQ6B6SEEP'
